services:
  - type: web
    name: aaditya-ecommerce-store
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: aaditya-ecommerce-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: aaditya-ecommerce-store.onrender.com,localhost,127.0.0.1
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: postgres
    name: aaditya-ecommerce-db
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
