services:
  - type: web
    name: aaditya-ecommerce-store
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHONUNBUFFERED
        value: "1"
